site_name: Zen BBQ 1.2 for Blender
site_description: Zen BBQ 1.2 for Blender Documentation
nav:
    - Introduction: index.md
    - Installation: installation.md
    - Quick Start: quickstart.md
    - N-Panel: npanel.md
    - Pie Menu: piemenu.md
    - Downloads: downloads.md
    - How to Bake Normal Map: bake-tutor-1.md
    - How to use vertex color mask: guide_using_vc_mask.md
    - Troubleshooting: troubleshooting.md
    - Changelog:
        - Changelog: changelog.md
        - Version 1.2.0: changelog/release_note_1.2.0.md
        - Version 1.1.0: changelog/release_note_1.1.0.md
docs_dir: mkdocs
site_dir: docs
theme: readthedocs
markdown_extensions:
    - smarty
    - admonition